---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.x
    - tip
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - make all
    - make cover
    - make release
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  deploy:
    provider: releases
    api_key:
      secure: "ywvDIXtIwI8aOAazBZqwgwVpM+4wRqLWCCBcZUsOdGPwiQlWZW1f6cR78+90GETitzv/SucdEja0iFT+D1nrYbAX9fb6vRC+6FWBBSujD1mFmlHOiU2Yw2TQ8MKv6ZbGN7svjovLE73okhf4LEneiqkPUoJzrQv4Oy8IWwakuXcLRFBwCtveYWDepaEZDXhqiaGvrYAnWbaPb8Wjp2qz3Ep959UoCi3Xtr5RxiwK3LtHFMupy/3wuB5R9b0pZzWwbbA/vU1DquDwKazKQbelf0PvRJ0pKNWMS0L1SWn87j4hRslozyFQsKbM6oJElYlYdgpPkuhqEmyQZSUoqY9CKa5bsq2LBI9pl+b+oZq2RR6Jv+3ZN5ii/y9qJKFyF+DpKJc+WFdrMNYU59n74VsySdz0TjkSO9B3nyTdk/ySE+Fpekgr1rV6H39KnrVph+FrGZ8Ah3L+Kt/+YwYaYafp/dHApChpVfjLSfpWXuT5ussioY/cWxaaTQUFGTNO0LQ3k4JsThc6oQzpwqaAaMDWyoAHXWuPNsZIYlfKGb3CsGBVvcNKWxOwczsJpVx9vYKZuu85xpdCsA3BiU8qDIguAPaJJYAUBHAzkJsOwvMofTxNb0SRm12zYJpzfItt4e4Xcl7rBid1dTAlBgMHAjhJDsr6SpYp+y3lgWpRVNJirIo="
    file:
      - cross/snippetlib-linux-amd64.md5
      - cross/snippetlib-windows-386.sha256
      - cross/snippetlib-linux-arm
      - cross/snippetlib-darwin-amd64.md5
      - cross/snippetlib-darwin-amd64
      - cross/snippetlib-solaris-amd64.md5
      - cross/snippetlib-linux-arm64.sha256
      - cross/snippetlib-linux-arm.sha256
      - cross/snippetlib-linux-386.sha256
      - cross/snippetlib-darwin-386.md5
      - cross/snippetlib-windows-386.md5
      - cross/snippetlib-freebsd-amd64.md5
      - cross/snippetlib-linux-arm64.md5
      - cross/snippetlib-linux-arm64
      - cross/snippetlib-freebsd-amd64.sha256
      - cross/snippetlib-freebsd-386.md5
      - cross/snippetlib-linux-amd64.sha256
      - cross/snippetlib-linux-386.md5
      - cross/snippetlib-freebsd-386
      - cross/snippetlib-solaris-amd64.sha256
      - cross/snippetlib-windows-amd64
      - cross/snippetlib-windows-amd64.md5
      - cross/snippetlib-windows-amd64.sha256
      - cross/snippetlib-linux-arm.md5
      - cross/snippetlib-darwin-386.sha256
      - cross/snippetlib-darwin-amd64.sha256
      - cross/snippetlib-windows-386
      - cross/snippetlib-solaris-amd64
      - cross/snippetlib-darwin-386
      - cross/snippetlib-linux-386
      - cross/snippetlib-freebsd-amd64
      - cross/snippetlib-freebsd-386.sha256
      - cross/snippetlib-linux-amd64
    skip_cleanup: true
    on:
      tags: true
